#!/bin/bash
#a script to build and deploy the ICTIT Tabletop Tournament management project

#Install ASP.Net sdk
wget -q packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1.105

#Install Apache2
sudo apt-get install apache2

#Configute Apache2 to act as a reverse proxy
sudo a2enmod proxy proxy_http proxy_html


sudo echo "<VirtualHost *:80>
ProxyPreserveHost On
ProxyPass / http://127.0.0.1:63792/
ProxyPassReverse / http://127.0.0.1:63792/
ErrorLog /var/log/apache2/TabelTopCoreWeb-error.log
CustomLog /var/log/apache2/TabelTopCoreWeb-access.log common
</VirtualHost>" >> /etc/apache2/conf-enabled/TabelTopCoreWeb.conf

#restart apache
sudo service apache2 restart

#Set apache to manage kestrel server



sudo echo "[Unit]
Description=TableTop ASP .NET Web Application running on Ubuntu 16.04
[Service]
WorkingDirectory=/home/ubuntu/TableTop2017CoreWeb/TableTop2017CoreWeb/bin/Release
ExecStart=/usr/bin/dotnet /usr/bin/dotnet /home/ubuntu/TableTop2017CoreWeb/TableTop2017CoreWeb/bin/Release/netcoreapp2.0/TableTop2017CoreWeb.dll
Restart=always
RestartSec=10
SyslogIdentifier=tabletop
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Production
[Install]
WantedBy=multi-user.target" >> /etc/systemd/system/kestrel-TableTopCoreWeb.service

#Enable and start service
sudo systemctl enable kestrel-TableTopCoreWeb.service

sudo systemctl start kestrel-TableTopCoreWeb.service

#Build and start application
cd /home/ubuntu/TableTop2017CoreWeb/TableTop2017CoreWeb

dotnet restore

dotnet ef database update --context TournamentDbContext
